sudo: required
services: 
    - docker
language: cpp
compiler: g++
install:
    - if [ $TRAVIS_OS_NAME == osx ]; then 
           brew update 
        && brew unlink  boost 
        && brew install boost 
        && brew link --force boost
        && brew unlink  cmake
        && brew install cmake 
        && brew link --force cmake;
      fi
script: 
    - if [ $TRAVIS_OS_NAME == osx ]; then 
          cd build && cmake .. && make && make test;
      fi
    - if [ $TRAVIS_OS_NAME == linux ]; then 
          docker build . ;
      fi
branches:
    only:
    - master
notification:
    email: true
os:
- linux
- osx
